version: "2"
services:
  sirineapp-frontend:
    image: localhost/sirineapp-frontend
    build: .
    container_name: sirineapp-frontend
    restart: unless-stopped
    volumes:
      - .env:/app/.env
      - ./src:/app/src
    ports:
      - "3000:3000"
networks:
  db:
    external: true
